language: ruby
rvm:
- 2.1.5
env:
- DB=postgresql
before_script:
- cp config/database.dev.yml config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rake db:migrate RAILS_ENV=test --trace
- bundle exec rake db:test:prepare
- bundle exec rake
addons:
  code_climate:
    repo_token: 3a8a7cbb21c0edd76711818c502cdb0d9033b0d51c355f9109abfe02a40b329c

