# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e73e317fe77a570bcfa7676e7b6d589e05dd0e99bdc19854e6ee84d44d9ae96034e31615ef7f3ef29e50fa6780ef1dedf5bbaca98181205ccf0ba8152852054

test:
  secret_key_base: 507cdc88d6c189eb2f82758bb46c9348946fa2b18a8f9ab4bc763e201146109482dd8b94d895663e6f69ccb46a5d5a38b875b37b2330a2c9033f1c013e303ac0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
