test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  openexchange_api_id: <%= ENV["OPENEXCHANGE_API_ID"] %>
  openexchange_url: <%= ENV["OPENEXCHANGE_URL"] %>
  openexchange_source_name: <%= ENV["OPENEXCHANGE_SOURCE_NAME"] %>
  appspot_api_id: <%= ENV["APPSPOT_API_ID"] %>
  appspot_url: <%= ENV["APPSPOT_URL"] %>
  appspot_source_name: <%= ENV["APPSPOT_SOURCE_NAME"] %>
  ecb_int_url: <%= ENV["ECB_INT_URL"] %>
  ecb_int_source_name: <%= ENV["ECB_INT_SOURCE_NAME"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  openexchange_api_id: <%= ENV["OPENEXCHANGE_API_ID"] %>
  openexchange_url: <%= ENV["OPENEXCHANGE_URL"] %>
  openexchange_source_name: <%= ENV["OPENEXCHANGE_SOURCE_NAME"] %>
  appspot_api_id: <%= ENV["APPSPOT_API_ID"] %>
  appspot_url: <%= ENV["APPSPOT_URL"] %>
  appspot_source_name: <%= ENV["APPSPOT_SOURCE_NAME"] %>
  ecb_int_url: <%= ENV["ECB_INT_URL"] %>
  ecb_int_source_name: <%= ENV["ECB_INT_SOURCE_NAME"] %>
