development:
  secret_key_base: 7e73e317fe77a570bcfa7676e7b6d589e05dd0e99bdc19854e6ee84d44d9ae96034e31615ef7f3ef29e50fa6780ef1dedf5bbaca98181205ccf0ba8152852054
  openexchange_api_id: 112ab4d1dce843f68573bfd1260b49ac
  openexchange_url: "https://www.openexchangerates.org/api/latest.json"
  openexchange_source_name: "openexchangerates.org"
  appspot_api_id: e109de15118490870d2e3d53477efd2dc3d2ef31
  appspot_url: "http://currency-api.appspot.com/api"
  appspot_source_name: "appspot.com"
  ecb_int_url: "http://www.ecb.int/stats/eurofxref/eurofxref-daily.xml"
  ecb_int_source_name: "ecb.int"

test:
  secret_key_base: 507cdc88d6c189eb2f82758bb46c9348946fa2b18a8f9ab4bc763e201146109482dd8b94d895663e6f69ccb46a5d5a38b875b37b2330a2c9033f1c013e303ac0
  openexchange_api_id: 112ab4d1dce843f68573bfd1260b49ac
  openexchange_url: "https://www.openexchangerates.org/api/latest.json"
  openexchange_source_name: "openexchangerates.org"
  appspot_api_id: e109de15118490870d2e3d53477efd2dc3d2ef31
  appspot_url: "http://currency-api.appspot.com/api"
  appspot_source_name: "appspot.com"
  ecb_int_url: "http://www.ecb.int/stats/eurofxref/eurofxref-daily.xml"
  ecb_int_source_name: "ecb.int"

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  openexchange_api_id: <%= ENV["OPENEXCHANGE_API_ID"] %>
  openexchange_url: <%= ENV["OPENEXCHANGE_URL"] %>
  openexchange_source_name: <%= ENV["OPENEXCHANGE_SOURCE_NAME"] %>
  appspot_api_id: <%= ENV["APPSPOT_API_ID"] %>
  appspot_url: <%= ENV["APPSPOT_URL"] %>
  appspot_source_name: <%= ENV["APPSPOT_SOURCE_NAME"] %>
  ecb_int_url: <%= ENV["ECB_INT_URL"] %>
  ecb_int_source_name: <%= ENV["ECB_INT_SOURCE_NAME"] %>
